spring:
  rabbitmq:
    port: 5672
    host: 192.168.44.128
    #开启发送失败返回
    publisher-returns: true
    listener:
      simple:
        #指定最小的消费者数量.
        concurrency: 3
        #指定最大的消费者数量.
        max-concurrency: 3
        #开启ack
        acknowledge-mode: auto
      type: simple
      #开启ack
    #      direct:
#        acknowledge-mode: auto
    #支持消息的确认与返回
    template:
      mandatory: true
    publisher-confirm-type: correlated

